spring:
  jpa:
    open-in-view: false

openapi:
  service-key: ${OPENAPI_SERVICE_KEY}



---
spring:
  config:
    activate:
      on-profile: local
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: trace
    com:
      nbe2: DEBUG

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

naver:
  directions-clinet-id: ${NAVER_MAP_CLIENT_ID}
  directions-screat-key: ${NAVER_MAP_SCREAT_KEY}

---
spring:
  config:
    activate:
      on-profile: dev
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}