spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

server:
  shutdown: graceful

file:
  upload:
    path: ${FILE_UPLOAD_PATH}/Users/kangjiwon/Desktop/Projects/DevCourse/prac829/files/

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev