spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local
jwt:
  screat-key: ${JWT_KEY}

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  screat-key: ${JWT_KEY}