spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local
jwt:
  key: ${JWY_KEY}

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  key: ${JWY_KEY}