spring:
  config:
    activate:
      on-profile: local
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    client-id: ${KAKAO_REST_API_KEY}
    redirect-url: http://localhost:8080/api/v1/oauth/login
---
spring:
  config:
    activate:
      on-profile: dev
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    client-id: ${KAKAO_REST_API_KEY}
    redirect-url: ${KAKAO_REDIRECT_URL}